<script setup>
<<<<<<< HEAD
import { ref } from "vue";
=======
>>>>>>> origin/Website
const { blok } = defineProps({ blok: Object });
</script>
<template>
  <section
    v-editable="blok"
    class="container mx-auto flex flex-col pt-2 lg:flex-row"
  >
    <div
      class="info-text flex w-full flex-col justify-center gap-5 lg:w-1/3 xl:w-2/3"
    >
<<<<<<< HEAD
      <div class="text flex flex-col gap-5">
=======
      <div class="text slide-in-left flex flex-col gap-5">
>>>>>>> origin/Website
        <div class="hi my-10 self-center sm:self-auto">
          <div
            class="hi-container w-28 rounded bg-orange-theme py-2 text-center"
          >
            <p>{{ blok.welcomeText }}</p>
          </div>
        </div>
        <div class="titel-text flex flex-col text-center sm:text-left">
          <h1
            class="mb-6 text-[49px] font-bold leading-10 sm:font-black md:w-[673px]"
          >
            {{ blok.title }}
          </h1>
          <p>{{ blok.slug }}</p>
        </div>
      </div>
<<<<<<< HEAD
      <div class="hidden gap-6 sm:flex">
=======
      <div class="slide-in-left hidden gap-6 sm:flex">
>>>>>>> origin/Website
        <div class="data my-10 flex w-20 flex-col justify-center gap-1">
          <div
            class="data-1 flex h-16 w-16 items-center justify-center self-center rounded-full bg-white-theme"
          >
            {{ blok.ideeen }}+
          </div>
<<<<<<< HEAD
          <p class="text-center">ideeën</p>
        </div>
        <div class="data my-10 flex w-20 flex-col justify-center gap-1">
          <div
            class="data-1 flex h-16 w-16 items-center justify-center self-center rounded-full bg-white-theme"
          >
            {{ blok.ideeen }}+
          </div>
          <p class="text-center">Projecten</p>
        </div>
      </div>
    </div>
    <div class="jelmerFoto relative w-full sm:mt-[-100px] lg:mt-0">
      <img :src="blok.heroImg.filename" :alt="blok.heroImg.alt" class="" />
      <img
        src="https://a.storyblok.com/f/196239/354x353/4c01ffa1ec/ellipse-2.svg"
        alt="ellipse"
        class="lg-w-52 xl:w-50 animate absolute top-[5%] right-[20%] z-[-2] w-28 sm:w-52 lg:top-[6%] lg:right-[15%] 2xl:top-[5%] 2xl:right-[20%] 2xl:w-64"
=======
          <p class="text-center">Ideeën</p>
        </div>
        <div class="data my-10 flex w-20 flex-col justify-center gap-1">
          <div
            class="data-2 flex h-16 w-16 items-center justify-center self-center rounded-full bg-white-theme"
          >
            {{ blok.project }}+
          </div>
          <p class="text-center">projecten</p>
        </div>
      </div>
    </div>
    <div
      class="jelmerFoto relative w-full overflow-hidden sm:mt-[-100px] lg:mt-[16px]"
    >
      <img :src="blok.heroImg.filename" :alt="blok.heroImg.alt" />
      <img
        src="https://a.storyblok.com/f/196239/354x353/4c01ffa1ec/ellipse-2.svg"
        alt="ellipse"
        class="scale-up-center absolute top-[5%] right-[20%] z-[-2] w-28 sm:w-52 lg:top-[6%] lg:right-[15%] lg:w-52 2xl:top-[5%] 2xl:right-[20%] 2xl:w-64"
>>>>>>> origin/Website
      />
      <img
        src="https://a.storyblok.com/f/196239/354x353/d000ca7ec0/ellipse-1.svg"
        alt="ellipse"
<<<<<<< HEAD
        class="animate absolute left-[25%] bottom-[30%] z-[-2] w-28 sm:w-52 lg:left-[30%] lg:bottom-[30%] lg:w-52 2xl:left-[25%] 2xl:bottom-[30%] 2xl:w-64"
=======
        class="scale-up-center absolute left-[25%] bottom-[30%] z-[-2] w-28 sm:w-52 lg:left-[30%] lg:bottom-[30%] lg:w-52 2xl:left-[25%] 2xl:bottom-[30%] 2xl:w-64"
>>>>>>> origin/Website
      />
    </div>
  </section>
</template>
<<<<<<< HEAD
=======
<style>
.slide-in-left {
  -webkit-animation: slide-in-left 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-left 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
.scale-up-center {
  -webkit-animation: scale-up-center 0.8s cubic-bezier(0.39, 0.575, 0.565, 1)
    both;
  animation: scale-up-center 0.8s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
.scale-in-top {
  -webkit-animation: scale-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-3-9 17:27:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2023-3-9 17:31:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2023-3-9 18:56:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-top
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-top {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 50% 0%;
    transform-origin: 50% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 0%;
    transform-origin: 50% 0%;
    opacity: 1;
  }
}
@keyframes scale-in-top {
  0% {
    -webkit-transform: scale(0);
    transform: scale(0);
    -webkit-transform-origin: 50% 0%;
    transform-origin: 50% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 0%;
    transform-origin: 50% 0%;
    opacity: 1;
  }
}
</style>
>>>>>>> origin/Website
